---
title: checkmirrors
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    img-url: ''
    categories: Testimonials
email: checkmirrors@gmail.com
description: York driving instructors, checkmirrors, is a School of Motoring based
  in York with over 14 years experience. Book today from just £26 per hour with Pass
  Plus options available in York.
pricePerLesson: "£26"
priceForTen: "£250"
baseurl:
url: https://www.checkmirrors.co.uk
markdown: kramdown
year:
pass-date:
